/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#0d1c2f",
        "primary": "#000000",
        "secondary": "#006399",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#94ccff",
        "inverse-surface": "#213145",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary-fixed": "#131b2e",
        "on-primary-container": "#7c839b",
        "on-surface": "#0b1c30",
        "on-secondary-fixed": "#001d32",
        "on-secondary-fixed-variant": "#004b74",
        "tertiary-fixed-dim": "#b9c7e0",
        "background": "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "on-tertiary-container": "#76859b",
        "on-tertiary-fixed-variant": "#3a485c",
        "surface": "#f8f9ff",
        "on-error-container": "#93000a",
        "tertiary": "#000000",
        "outline-variant": "#c6c6cd",
        "on-secondary-container": "#004f7b",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed": "#d5e3fd",
        "on-error": "#ffffff",
        "outline": "#76777d",
        "on-background": "#0b1c30",
        "inverse-primary": "#bec6e0",
        "surface-dim": "#cbdbf5",
        "surface-container-highest": "#d3e4fe",
        "error": "#ba1a1a",
        "on-surface-variant": "#45464d",
        "primary-container": "#131b2e",
        "surface-container": "#e5eeff",
        "primary-fixed": "#dae2fd",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed-dim": "#bec6e0",
        "surface-tint": "#565e74",
        "secondary-fixed": "#cde5ff",
        "secondary-container": "#7bc2ff",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-container": "#0d1c2f",
        "surface-bright": "#f8f9ff",
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.25rem",
        "space-2xl": "1.5rem",
        "gutter-table": "0.75rem",
        "margin-screen": "1.5rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
